language: java
jdk:
  - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

env:
  - RUN_PMD=true
  - RUN_PMD=false

matrix:
  allow_failures:
    - env: RUN_PMD=true

script:
  - mvn test
  - if $RUN_PMD ; then mvn pmd:check ; fi
  - if $RUN_PMD ; then mvn pmd:cpd-check ; fi