language: java
jdk:
  - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

env:
  - MAY_FAIL=true
  - MAY_FAIL=false

matrix:
  allow_failures:
    - env: MAY_FAIL=true

script:
  - mvn test
  - if $MAY_FAIL ; then mvn pmd:check ; fi
  - if $MAY_FAIL ; then mvn pmd:cpd-check ; fi
  - if $MAY_FAIL ; then mvn checkstyle:check ; fi
